<?xml version="1.0"?>
<package format="3">
  <name>robbdd_tutorials</name>
  <version>0.1.0</version>
  <description>Models and launch files for the RobBDD tutorials.</description>
  <maintainer email="1168534+minhnh@users.noreply.github.com">Minh Nguyen</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <exec_depend>bdd_bt_executor_ros2</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>bdd_exec_ros2</exec_depend>
  <exec_depend>bdd_ros2_interfaces</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
